[project]
name = 'democratic-governance-platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.proposal-engine]
path = 'contracts/proposal-engine.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting-booth]
path = 'contracts/voting-booth.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
